/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_gpio.h"

static const char* CMockString_gpio_config = "gpio_config";
static const char* CMockString_pGPIOConfig = "pGPIOConfig";

typedef struct _CMOCK_gpio_config_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const gpio_config_t* Expected_pGPIOConfig;

} CMOCK_gpio_config_CALL_INSTANCE;

static struct mock_gpioInstance
{
  char gpio_config_IgnoreBool;
  esp_err_t gpio_config_FinalReturn;
  char gpio_config_CallbackBool;
  CMOCK_gpio_config_CALLBACK gpio_config_CallbackFunctionPointer;
  int gpio_config_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE gpio_config_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_gpio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.gpio_config_CallInstance;
  if (Mock.gpio_config_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_config);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.gpio_config_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_gpio_Init(void)
{
  mock_gpio_Destroy();
}

void mock_gpio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t gpio_config(const gpio_config_t* pGPIOConfig)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_config_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_config);
  cmock_call_instance = (CMOCK_gpio_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_config_CallInstance);
  Mock.gpio_config_CallInstance = CMock_Guts_MemNext(Mock.gpio_config_CallInstance);
  if (Mock.gpio_config_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.gpio_config_FinalReturn;
    memcpy((void*)(&Mock.gpio_config_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.gpio_config_CallbackBool &&
      Mock.gpio_config_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.gpio_config_CallbackFunctionPointer(pGPIOConfig, Mock.gpio_config_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_gpio_config,CMockString_pGPIOConfig);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGPIOConfig), (void*)(pGPIOConfig), sizeof(const gpio_config_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.gpio_config_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.gpio_config_CallbackFunctionPointer(pGPIOConfig, Mock.gpio_config_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_gpio_config(CMOCK_gpio_config_CALL_INSTANCE* cmock_call_instance, const gpio_config_t* pGPIOConfig);
void CMockExpectParameters_gpio_config(CMOCK_gpio_config_CALL_INSTANCE* cmock_call_instance, const gpio_config_t* pGPIOConfig)
{
  cmock_call_instance->Expected_pGPIOConfig = pGPIOConfig;
}

void gpio_config_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_config_CALL_INSTANCE));
  CMOCK_gpio_config_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_config_CallInstance = CMock_Guts_MemChain(Mock.gpio_config_CallInstance, cmock_guts_index);
  Mock.gpio_config_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.gpio_config_IgnoreBool = (char)1;
}

void gpio_config_CMockStopIgnore(void)
{
  if(Mock.gpio_config_IgnoreBool)
    Mock.gpio_config_CallInstance = CMock_Guts_MemNext(Mock.gpio_config_CallInstance);
  Mock.gpio_config_IgnoreBool = (char)0;
}

void gpio_config_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const gpio_config_t* pGPIOConfig, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_config_CALL_INSTANCE));
  CMOCK_gpio_config_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_config_CallInstance = CMock_Guts_MemChain(Mock.gpio_config_CallInstance, cmock_guts_index);
  Mock.gpio_config_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_gpio_config(cmock_call_instance, pGPIOConfig);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void gpio_config_AddCallback(CMOCK_gpio_config_CALLBACK Callback)
{
  Mock.gpio_config_IgnoreBool = (char)0;
  Mock.gpio_config_CallbackBool = (char)1;
  Mock.gpio_config_CallbackFunctionPointer = Callback;
}

void gpio_config_Stub(CMOCK_gpio_config_CALLBACK Callback)
{
  Mock.gpio_config_IgnoreBool = (char)0;
  Mock.gpio_config_CallbackBool = (char)0;
  Mock.gpio_config_CallbackFunctionPointer = Callback;
}

