/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_i2c_master.h"

static const char* CMockString_bus_config = "bus_config";
static const char* CMockString_i2c_new_master_bus = "i2c_new_master_bus";
static const char* CMockString_ret_handle = "ret_handle";

typedef struct _CMOCK_i2c_new_master_bus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const i2c_master_bus_config_t* Expected_bus_config;
  i2c_master_bus_handle_t* Expected_ret_handle;

} CMOCK_i2c_new_master_bus_CALL_INSTANCE;

static struct mock_i2c_masterInstance
{
  char i2c_new_master_bus_IgnoreBool;
  esp_err_t i2c_new_master_bus_FinalReturn;
  char i2c_new_master_bus_CallbackBool;
  CMOCK_i2c_new_master_bus_CALLBACK i2c_new_master_bus_CallbackFunctionPointer;
  int i2c_new_master_bus_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_new_master_bus_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_i2c_master_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.i2c_new_master_bus_CallInstance;
  if (Mock.i2c_new_master_bus_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_i2c_new_master_bus);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.i2c_new_master_bus_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_i2c_master_Init(void)
{
  mock_i2c_master_Destroy();
}

void mock_i2c_master_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t i2c_new_master_bus(const i2c_master_bus_config_t* bus_config, i2c_master_bus_handle_t* ret_handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_new_master_bus_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_new_master_bus);
  cmock_call_instance = (CMOCK_i2c_new_master_bus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_new_master_bus_CallInstance);
  Mock.i2c_new_master_bus_CallInstance = CMock_Guts_MemNext(Mock.i2c_new_master_bus_CallInstance);
  if (Mock.i2c_new_master_bus_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.i2c_new_master_bus_FinalReturn;
    memcpy((void*)(&Mock.i2c_new_master_bus_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.i2c_new_master_bus_CallbackBool &&
      Mock.i2c_new_master_bus_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.i2c_new_master_bus_CallbackFunctionPointer(bus_config, ret_handle, Mock.i2c_new_master_bus_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_i2c_new_master_bus,CMockString_bus_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bus_config), (void*)(bus_config), sizeof(const i2c_master_bus_config_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_i2c_new_master_bus,CMockString_ret_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ret_handle), (void*)(ret_handle), sizeof(i2c_master_bus_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.i2c_new_master_bus_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.i2c_new_master_bus_CallbackFunctionPointer(bus_config, ret_handle, Mock.i2c_new_master_bus_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_i2c_new_master_bus(CMOCK_i2c_new_master_bus_CALL_INSTANCE* cmock_call_instance, const i2c_master_bus_config_t* bus_config, i2c_master_bus_handle_t* ret_handle);
void CMockExpectParameters_i2c_new_master_bus(CMOCK_i2c_new_master_bus_CALL_INSTANCE* cmock_call_instance, const i2c_master_bus_config_t* bus_config, i2c_master_bus_handle_t* ret_handle)
{
  cmock_call_instance->Expected_bus_config = bus_config;
  cmock_call_instance->Expected_ret_handle = ret_handle;
}

void i2c_new_master_bus_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_new_master_bus_CALL_INSTANCE));
  CMOCK_i2c_new_master_bus_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_new_master_bus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_new_master_bus_CallInstance = CMock_Guts_MemChain(Mock.i2c_new_master_bus_CallInstance, cmock_guts_index);
  Mock.i2c_new_master_bus_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.i2c_new_master_bus_IgnoreBool = (char)1;
}

void i2c_new_master_bus_CMockStopIgnore(void)
{
  if(Mock.i2c_new_master_bus_IgnoreBool)
    Mock.i2c_new_master_bus_CallInstance = CMock_Guts_MemNext(Mock.i2c_new_master_bus_CallInstance);
  Mock.i2c_new_master_bus_IgnoreBool = (char)0;
}

void i2c_new_master_bus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const i2c_master_bus_config_t* bus_config, i2c_master_bus_handle_t* ret_handle, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_new_master_bus_CALL_INSTANCE));
  CMOCK_i2c_new_master_bus_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_new_master_bus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_new_master_bus_CallInstance = CMock_Guts_MemChain(Mock.i2c_new_master_bus_CallInstance, cmock_guts_index);
  Mock.i2c_new_master_bus_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_i2c_new_master_bus(cmock_call_instance, bus_config, ret_handle);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void i2c_new_master_bus_AddCallback(CMOCK_i2c_new_master_bus_CALLBACK Callback)
{
  Mock.i2c_new_master_bus_IgnoreBool = (char)0;
  Mock.i2c_new_master_bus_CallbackBool = (char)1;
  Mock.i2c_new_master_bus_CallbackFunctionPointer = Callback;
}

void i2c_new_master_bus_Stub(CMOCK_i2c_new_master_bus_CALLBACK Callback)
{
  Mock.i2c_new_master_bus_IgnoreBool = (char)0;
  Mock.i2c_new_master_bus_CallbackBool = (char)0;
  Mock.i2c_new_master_bus_CallbackFunctionPointer = Callback;
}

