/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_ESP_LCD_PANEL_VENDOR_H
#define _MOCK_ESP_LCD_PANEL_VENDOR_H

#include "unity.h"
#include "driver/i2c_master.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_vendor.h"
#include "esp_lcd_panel_ops.h"
#include "driver/gpio.h"
#include "esp_lcd_panel_vendor.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_esp_lcd_panel_vendor_Init(void);
void mock_esp_lcd_panel_vendor_Destroy(void);
void mock_esp_lcd_panel_vendor_Verify(void);




#define esp_lcd_panel_init_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_init requires _IgnoreAndReturn");
#define esp_lcd_panel_init_IgnoreAndReturn(cmock_retval) esp_lcd_panel_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_init_StopIgnore() esp_lcd_panel_init_CMockStopIgnore()
void esp_lcd_panel_init_CMockStopIgnore(void);
#define esp_lcd_panel_init_Expect(panel) TEST_FAIL_MESSAGE("esp_lcd_panel_init requires _ExpectAndReturn");
#define esp_lcd_panel_init_ExpectAndReturn(panel, cmock_retval) esp_lcd_panel_init_CMockExpectAndReturn(__LINE__, panel, cmock_retval)
void esp_lcd_panel_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_init_CALLBACK)(esp_lcd_panel_handle_t panel, int cmock_num_calls);
void esp_lcd_panel_init_AddCallback(CMOCK_esp_lcd_panel_init_CALLBACK Callback);
void esp_lcd_panel_init_Stub(CMOCK_esp_lcd_panel_init_CALLBACK Callback);
#define esp_lcd_panel_init_StubWithCallback esp_lcd_panel_init_Stub
#define esp_lcd_panel_reset_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_reset requires _IgnoreAndReturn");
#define esp_lcd_panel_reset_IgnoreAndReturn(cmock_retval) esp_lcd_panel_reset_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_reset_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_reset_StopIgnore() esp_lcd_panel_reset_CMockStopIgnore()
void esp_lcd_panel_reset_CMockStopIgnore(void);
#define esp_lcd_panel_reset_Expect(panel) TEST_FAIL_MESSAGE("esp_lcd_panel_reset requires _ExpectAndReturn");
#define esp_lcd_panel_reset_ExpectAndReturn(panel, cmock_retval) esp_lcd_panel_reset_CMockExpectAndReturn(__LINE__, panel, cmock_retval)
void esp_lcd_panel_reset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_reset_CALLBACK)(esp_lcd_panel_handle_t panel, int cmock_num_calls);
void esp_lcd_panel_reset_AddCallback(CMOCK_esp_lcd_panel_reset_CALLBACK Callback);
void esp_lcd_panel_reset_Stub(CMOCK_esp_lcd_panel_reset_CALLBACK Callback);
#define esp_lcd_panel_reset_StubWithCallback esp_lcd_panel_reset_Stub
#define esp_lcd_panel_invert_color_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_invert_color requires _IgnoreAndReturn");
#define esp_lcd_panel_invert_color_IgnoreAndReturn(cmock_retval) esp_lcd_panel_invert_color_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_invert_color_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_invert_color_StopIgnore() esp_lcd_panel_invert_color_CMockStopIgnore()
void esp_lcd_panel_invert_color_CMockStopIgnore(void);
#define esp_lcd_panel_invert_color_Expect(panel, invert_color_data) TEST_FAIL_MESSAGE("esp_lcd_panel_invert_color requires _ExpectAndReturn");
#define esp_lcd_panel_invert_color_ExpectAndReturn(panel, invert_color_data, cmock_retval) esp_lcd_panel_invert_color_CMockExpectAndReturn(__LINE__, panel, invert_color_data, cmock_retval)
void esp_lcd_panel_invert_color_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool invert_color_data, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_invert_color_CALLBACK)(esp_lcd_panel_handle_t panel, bool invert_color_data, int cmock_num_calls);
void esp_lcd_panel_invert_color_AddCallback(CMOCK_esp_lcd_panel_invert_color_CALLBACK Callback);
void esp_lcd_panel_invert_color_Stub(CMOCK_esp_lcd_panel_invert_color_CALLBACK Callback);
#define esp_lcd_panel_invert_color_StubWithCallback esp_lcd_panel_invert_color_Stub
#define esp_lcd_panel_set_gap_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_set_gap requires _IgnoreAndReturn");
#define esp_lcd_panel_set_gap_IgnoreAndReturn(cmock_retval) esp_lcd_panel_set_gap_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_set_gap_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_set_gap_StopIgnore() esp_lcd_panel_set_gap_CMockStopIgnore()
void esp_lcd_panel_set_gap_CMockStopIgnore(void);
#define esp_lcd_panel_set_gap_Expect(panel, x_gap, y_gap) TEST_FAIL_MESSAGE("esp_lcd_panel_set_gap requires _ExpectAndReturn");
#define esp_lcd_panel_set_gap_ExpectAndReturn(panel, x_gap, y_gap, cmock_retval) esp_lcd_panel_set_gap_CMockExpectAndReturn(__LINE__, panel, x_gap, y_gap, cmock_retval)
void esp_lcd_panel_set_gap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, int x_gap, int y_gap, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_set_gap_CALLBACK)(esp_lcd_panel_handle_t panel, int x_gap, int y_gap, int cmock_num_calls);
void esp_lcd_panel_set_gap_AddCallback(CMOCK_esp_lcd_panel_set_gap_CALLBACK Callback);
void esp_lcd_panel_set_gap_Stub(CMOCK_esp_lcd_panel_set_gap_CALLBACK Callback);
#define esp_lcd_panel_set_gap_StubWithCallback esp_lcd_panel_set_gap_Stub
#define esp_lcd_panel_mirror_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_mirror requires _IgnoreAndReturn");
#define esp_lcd_panel_mirror_IgnoreAndReturn(cmock_retval) esp_lcd_panel_mirror_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_mirror_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_mirror_StopIgnore() esp_lcd_panel_mirror_CMockStopIgnore()
void esp_lcd_panel_mirror_CMockStopIgnore(void);
#define esp_lcd_panel_mirror_Expect(panel, mirror_x, mirror_y) TEST_FAIL_MESSAGE("esp_lcd_panel_mirror requires _ExpectAndReturn");
#define esp_lcd_panel_mirror_ExpectAndReturn(panel, mirror_x, mirror_y, cmock_retval) esp_lcd_panel_mirror_CMockExpectAndReturn(__LINE__, panel, mirror_x, mirror_y, cmock_retval)
void esp_lcd_panel_mirror_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool mirror_x, bool mirror_y, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_mirror_CALLBACK)(esp_lcd_panel_handle_t panel, bool mirror_x, bool mirror_y, int cmock_num_calls);
void esp_lcd_panel_mirror_AddCallback(CMOCK_esp_lcd_panel_mirror_CALLBACK Callback);
void esp_lcd_panel_mirror_Stub(CMOCK_esp_lcd_panel_mirror_CALLBACK Callback);
#define esp_lcd_panel_mirror_StubWithCallback esp_lcd_panel_mirror_Stub
#define esp_lcd_panel_disp_on_off_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_disp_on_off requires _IgnoreAndReturn");
#define esp_lcd_panel_disp_on_off_IgnoreAndReturn(cmock_retval) esp_lcd_panel_disp_on_off_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_disp_on_off_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_disp_on_off_StopIgnore() esp_lcd_panel_disp_on_off_CMockStopIgnore()
void esp_lcd_panel_disp_on_off_CMockStopIgnore(void);
#define esp_lcd_panel_disp_on_off_Expect(panel, on_off) TEST_FAIL_MESSAGE("esp_lcd_panel_disp_on_off requires _ExpectAndReturn");
#define esp_lcd_panel_disp_on_off_ExpectAndReturn(panel, on_off, cmock_retval) esp_lcd_panel_disp_on_off_CMockExpectAndReturn(__LINE__, panel, on_off, cmock_retval)
void esp_lcd_panel_disp_on_off_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool on_off, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_disp_on_off_CALLBACK)(esp_lcd_panel_handle_t panel, bool on_off, int cmock_num_calls);
void esp_lcd_panel_disp_on_off_AddCallback(CMOCK_esp_lcd_panel_disp_on_off_CALLBACK Callback);
void esp_lcd_panel_disp_on_off_Stub(CMOCK_esp_lcd_panel_disp_on_off_CALLBACK Callback);
#define esp_lcd_panel_disp_on_off_StubWithCallback esp_lcd_panel_disp_on_off_Stub
#define esp_lcd_panel_swap_xy_Ignore() TEST_FAIL_MESSAGE("esp_lcd_panel_swap_xy requires _IgnoreAndReturn");
#define esp_lcd_panel_swap_xy_IgnoreAndReturn(cmock_retval) esp_lcd_panel_swap_xy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void esp_lcd_panel_swap_xy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define esp_lcd_panel_swap_xy_StopIgnore() esp_lcd_panel_swap_xy_CMockStopIgnore()
void esp_lcd_panel_swap_xy_CMockStopIgnore(void);
#define esp_lcd_panel_swap_xy_Expect(panel, swap_xy) TEST_FAIL_MESSAGE("esp_lcd_panel_swap_xy requires _ExpectAndReturn");
#define esp_lcd_panel_swap_xy_ExpectAndReturn(panel, swap_xy, cmock_retval) esp_lcd_panel_swap_xy_CMockExpectAndReturn(__LINE__, panel, swap_xy, cmock_retval)
void esp_lcd_panel_swap_xy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool swap_xy, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_esp_lcd_panel_swap_xy_CALLBACK)(esp_lcd_panel_handle_t panel, bool swap_xy, int cmock_num_calls);
void esp_lcd_panel_swap_xy_AddCallback(CMOCK_esp_lcd_panel_swap_xy_CALLBACK Callback);
void esp_lcd_panel_swap_xy_Stub(CMOCK_esp_lcd_panel_swap_xy_CALLBACK Callback);
#define esp_lcd_panel_swap_xy_StubWithCallback esp_lcd_panel_swap_xy_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
