/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_GPIO_H
#define _MOCK_GPIO_H

#include "unity.h"
#include "driver/i2c_master.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_vendor.h"
#include "esp_lcd_panel_ops.h"
#include "driver/gpio.h"
#include "gpio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_gpio_Init(void);
void mock_gpio_Destroy(void);
void mock_gpio_Verify(void);




#define gpio_config_Ignore() TEST_FAIL_MESSAGE("gpio_config requires _IgnoreAndReturn");
#define gpio_config_IgnoreAndReturn(cmock_retval) gpio_config_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void gpio_config_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define gpio_config_StopIgnore() gpio_config_CMockStopIgnore()
void gpio_config_CMockStopIgnore(void);
#define gpio_config_Expect(pGPIOConfig) TEST_FAIL_MESSAGE("gpio_config requires _ExpectAndReturn");
#define gpio_config_ExpectAndReturn(pGPIOConfig, cmock_retval) gpio_config_CMockExpectAndReturn(__LINE__, pGPIOConfig, cmock_retval)
void gpio_config_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const gpio_config_t* pGPIOConfig, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_gpio_config_CALLBACK)(const gpio_config_t* pGPIOConfig, int cmock_num_calls);
void gpio_config_AddCallback(CMOCK_gpio_config_CALLBACK Callback);
void gpio_config_Stub(CMOCK_gpio_config_CALLBACK Callback);
#define gpio_config_StubWithCallback gpio_config_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
