/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_I2C_MASTER_H
#define _MOCK_I2C_MASTER_H

#include "unity.h"
#include "driver/i2c_master.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_vendor.h"
#include "esp_lcd_panel_ops.h"
#include "driver/gpio.h"
#include "i2c_master.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_i2c_master_Init(void);
void mock_i2c_master_Destroy(void);
void mock_i2c_master_Verify(void);




#define i2c_new_master_bus_Ignore() TEST_FAIL_MESSAGE("i2c_new_master_bus requires _IgnoreAndReturn");
#define i2c_new_master_bus_IgnoreAndReturn(cmock_retval) i2c_new_master_bus_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void i2c_new_master_bus_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define i2c_new_master_bus_StopIgnore() i2c_new_master_bus_CMockStopIgnore()
void i2c_new_master_bus_CMockStopIgnore(void);
#define i2c_new_master_bus_Expect(bus_config, ret_handle) TEST_FAIL_MESSAGE("i2c_new_master_bus requires _ExpectAndReturn");
#define i2c_new_master_bus_ExpectAndReturn(bus_config, ret_handle, cmock_retval) i2c_new_master_bus_CMockExpectAndReturn(__LINE__, bus_config, ret_handle, cmock_retval)
void i2c_new_master_bus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const i2c_master_bus_config_t* bus_config, i2c_master_bus_handle_t* ret_handle, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_i2c_new_master_bus_CALLBACK)(const i2c_master_bus_config_t* bus_config, i2c_master_bus_handle_t* ret_handle, int cmock_num_calls);
void i2c_new_master_bus_AddCallback(CMOCK_i2c_new_master_bus_CALLBACK Callback);
void i2c_new_master_bus_Stub(CMOCK_i2c_new_master_bus_CALLBACK Callback);
#define i2c_new_master_bus_StubWithCallback i2c_new_master_bus_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
