/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_esp_lcd_panel_vendor.h"

static const char* CMockString_esp_lcd_panel_disp_on_off = "esp_lcd_panel_disp_on_off";
static const char* CMockString_esp_lcd_panel_init = "esp_lcd_panel_init";
static const char* CMockString_esp_lcd_panel_invert_color = "esp_lcd_panel_invert_color";
static const char* CMockString_esp_lcd_panel_mirror = "esp_lcd_panel_mirror";
static const char* CMockString_esp_lcd_panel_reset = "esp_lcd_panel_reset";
static const char* CMockString_esp_lcd_panel_set_gap = "esp_lcd_panel_set_gap";
static const char* CMockString_esp_lcd_panel_swap_xy = "esp_lcd_panel_swap_xy";
static const char* CMockString_invert_color_data = "invert_color_data";
static const char* CMockString_mirror_x = "mirror_x";
static const char* CMockString_mirror_y = "mirror_y";
static const char* CMockString_on_off = "on_off";
static const char* CMockString_panel = "panel";
static const char* CMockString_swap_xy = "swap_xy";
static const char* CMockString_x_gap = "x_gap";
static const char* CMockString_y_gap = "y_gap";

typedef struct _CMOCK_esp_lcd_panel_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;

} CMOCK_esp_lcd_panel_init_CALL_INSTANCE;

typedef struct _CMOCK_esp_lcd_panel_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;

} CMOCK_esp_lcd_panel_reset_CALL_INSTANCE;

typedef struct _CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;
  bool Expected_invert_color_data;

} CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE;

typedef struct _CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;
  int Expected_x_gap;
  int Expected_y_gap;

} CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE;

typedef struct _CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;
  bool Expected_mirror_x;
  bool Expected_mirror_y;

} CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE;

typedef struct _CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;
  bool Expected_on_off;

} CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE;

typedef struct _CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_lcd_panel_handle_t Expected_panel;
  bool Expected_swap_xy;

} CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE;

static struct mock_esp_lcd_panel_vendorInstance
{
  char esp_lcd_panel_init_IgnoreBool;
  esp_err_t esp_lcd_panel_init_FinalReturn;
  char esp_lcd_panel_init_CallbackBool;
  CMOCK_esp_lcd_panel_init_CALLBACK esp_lcd_panel_init_CallbackFunctionPointer;
  int esp_lcd_panel_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_init_CallInstance;
  char esp_lcd_panel_reset_IgnoreBool;
  esp_err_t esp_lcd_panel_reset_FinalReturn;
  char esp_lcd_panel_reset_CallbackBool;
  CMOCK_esp_lcd_panel_reset_CALLBACK esp_lcd_panel_reset_CallbackFunctionPointer;
  int esp_lcd_panel_reset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_reset_CallInstance;
  char esp_lcd_panel_invert_color_IgnoreBool;
  esp_err_t esp_lcd_panel_invert_color_FinalReturn;
  char esp_lcd_panel_invert_color_CallbackBool;
  CMOCK_esp_lcd_panel_invert_color_CALLBACK esp_lcd_panel_invert_color_CallbackFunctionPointer;
  int esp_lcd_panel_invert_color_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_invert_color_CallInstance;
  char esp_lcd_panel_set_gap_IgnoreBool;
  esp_err_t esp_lcd_panel_set_gap_FinalReturn;
  char esp_lcd_panel_set_gap_CallbackBool;
  CMOCK_esp_lcd_panel_set_gap_CALLBACK esp_lcd_panel_set_gap_CallbackFunctionPointer;
  int esp_lcd_panel_set_gap_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_set_gap_CallInstance;
  char esp_lcd_panel_mirror_IgnoreBool;
  esp_err_t esp_lcd_panel_mirror_FinalReturn;
  char esp_lcd_panel_mirror_CallbackBool;
  CMOCK_esp_lcd_panel_mirror_CALLBACK esp_lcd_panel_mirror_CallbackFunctionPointer;
  int esp_lcd_panel_mirror_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_mirror_CallInstance;
  char esp_lcd_panel_disp_on_off_IgnoreBool;
  esp_err_t esp_lcd_panel_disp_on_off_FinalReturn;
  char esp_lcd_panel_disp_on_off_CallbackBool;
  CMOCK_esp_lcd_panel_disp_on_off_CALLBACK esp_lcd_panel_disp_on_off_CallbackFunctionPointer;
  int esp_lcd_panel_disp_on_off_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_disp_on_off_CallInstance;
  char esp_lcd_panel_swap_xy_IgnoreBool;
  esp_err_t esp_lcd_panel_swap_xy_FinalReturn;
  char esp_lcd_panel_swap_xy_CallbackBool;
  CMOCK_esp_lcd_panel_swap_xy_CALLBACK esp_lcd_panel_swap_xy_CallbackFunctionPointer;
  int esp_lcd_panel_swap_xy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_lcd_panel_swap_xy_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_esp_lcd_panel_vendor_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.esp_lcd_panel_init_CallInstance;
  if (Mock.esp_lcd_panel_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_lcd_panel_reset_CallInstance;
  if (Mock.esp_lcd_panel_reset_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_reset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_reset_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_lcd_panel_invert_color_CallInstance;
  if (Mock.esp_lcd_panel_invert_color_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_invert_color);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_lcd_panel_set_gap_CallInstance;
  if (Mock.esp_lcd_panel_set_gap_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_set_gap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_lcd_panel_mirror_CallInstance;
  if (Mock.esp_lcd_panel_mirror_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_mirror);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_mirror_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_lcd_panel_disp_on_off_CallInstance;
  if (Mock.esp_lcd_panel_disp_on_off_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_disp_on_off);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_lcd_panel_swap_xy_CallInstance;
  if (Mock.esp_lcd_panel_swap_xy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_lcd_panel_swap_xy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_esp_lcd_panel_vendor_Init(void)
{
  mock_esp_lcd_panel_vendor_Destroy();
}

void mock_esp_lcd_panel_vendor_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t esp_lcd_panel_init(esp_lcd_panel_handle_t panel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_init);
  cmock_call_instance = (CMOCK_esp_lcd_panel_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_init_CallInstance);
  Mock.esp_lcd_panel_init_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_init_CallInstance);
  if (Mock.esp_lcd_panel_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_init_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_init_CallbackBool &&
      Mock.esp_lcd_panel_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_init_CallbackFunctionPointer(panel, Mock.esp_lcd_panel_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_init,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_init_CallbackFunctionPointer(panel, Mock.esp_lcd_panel_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_init(CMOCK_esp_lcd_panel_init_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel);
void CMockExpectParameters_esp_lcd_panel_init(CMOCK_esp_lcd_panel_init_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_init_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_init_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_init_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_init_IgnoreBool = (char)1;
}

void esp_lcd_panel_init_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_init_IgnoreBool)
    Mock.esp_lcd_panel_init_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_init_CallInstance);
  Mock.esp_lcd_panel_init_IgnoreBool = (char)0;
}

void esp_lcd_panel_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_init_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_init_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_init_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_init(cmock_call_instance, panel);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_init_AddCallback(CMOCK_esp_lcd_panel_init_CALLBACK Callback)
{
  Mock.esp_lcd_panel_init_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_init_CallbackBool = (char)1;
  Mock.esp_lcd_panel_init_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_init_Stub(CMOCK_esp_lcd_panel_init_CALLBACK Callback)
{
  Mock.esp_lcd_panel_init_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_init_CallbackBool = (char)0;
  Mock.esp_lcd_panel_init_CallbackFunctionPointer = Callback;
}

esp_err_t esp_lcd_panel_reset(esp_lcd_panel_handle_t panel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_reset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_reset);
  cmock_call_instance = (CMOCK_esp_lcd_panel_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_reset_CallInstance);
  Mock.esp_lcd_panel_reset_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_reset_CallInstance);
  if (Mock.esp_lcd_panel_reset_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_reset_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_reset_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_reset_CallbackBool &&
      Mock.esp_lcd_panel_reset_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_reset_CallbackFunctionPointer(panel, Mock.esp_lcd_panel_reset_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_reset,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_reset_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_reset_CallbackFunctionPointer(panel, Mock.esp_lcd_panel_reset_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_reset(CMOCK_esp_lcd_panel_reset_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel);
void CMockExpectParameters_esp_lcd_panel_reset(CMOCK_esp_lcd_panel_reset_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_reset_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_reset_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_reset_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_reset_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_reset_IgnoreBool = (char)1;
}

void esp_lcd_panel_reset_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_reset_IgnoreBool)
    Mock.esp_lcd_panel_reset_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_reset_CallInstance);
  Mock.esp_lcd_panel_reset_IgnoreBool = (char)0;
}

void esp_lcd_panel_reset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_reset_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_reset_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_reset_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_reset(cmock_call_instance, panel);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_reset_AddCallback(CMOCK_esp_lcd_panel_reset_CALLBACK Callback)
{
  Mock.esp_lcd_panel_reset_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_reset_CallbackBool = (char)1;
  Mock.esp_lcd_panel_reset_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_reset_Stub(CMOCK_esp_lcd_panel_reset_CALLBACK Callback)
{
  Mock.esp_lcd_panel_reset_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_reset_CallbackBool = (char)0;
  Mock.esp_lcd_panel_reset_CallbackFunctionPointer = Callback;
}

esp_err_t esp_lcd_panel_invert_color(esp_lcd_panel_handle_t panel, bool invert_color_data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_invert_color);
  cmock_call_instance = (CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_invert_color_CallInstance);
  Mock.esp_lcd_panel_invert_color_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_invert_color_CallInstance);
  if (Mock.esp_lcd_panel_invert_color_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_invert_color_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_invert_color_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_invert_color_CallbackBool &&
      Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer(panel, invert_color_data, Mock.esp_lcd_panel_invert_color_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_invert_color,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_invert_color,CMockString_invert_color_data);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_invert_color_data, invert_color_data, cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer(panel, invert_color_data, Mock.esp_lcd_panel_invert_color_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_invert_color(CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool invert_color_data);
void CMockExpectParameters_esp_lcd_panel_invert_color(CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool invert_color_data)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_invert_color_data = invert_color_data;
}

void esp_lcd_panel_invert_color_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_invert_color_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_invert_color_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_invert_color_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_invert_color_IgnoreBool = (char)1;
}

void esp_lcd_panel_invert_color_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_invert_color_IgnoreBool)
    Mock.esp_lcd_panel_invert_color_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_invert_color_CallInstance);
  Mock.esp_lcd_panel_invert_color_IgnoreBool = (char)0;
}

void esp_lcd_panel_invert_color_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool invert_color_data, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_invert_color_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_invert_color_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_invert_color_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_invert_color_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_invert_color(cmock_call_instance, panel, invert_color_data);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_invert_color_AddCallback(CMOCK_esp_lcd_panel_invert_color_CALLBACK Callback)
{
  Mock.esp_lcd_panel_invert_color_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_invert_color_CallbackBool = (char)1;
  Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_invert_color_Stub(CMOCK_esp_lcd_panel_invert_color_CALLBACK Callback)
{
  Mock.esp_lcd_panel_invert_color_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_invert_color_CallbackBool = (char)0;
  Mock.esp_lcd_panel_invert_color_CallbackFunctionPointer = Callback;
}

esp_err_t esp_lcd_panel_set_gap(esp_lcd_panel_handle_t panel, int x_gap, int y_gap)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_set_gap);
  cmock_call_instance = (CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_set_gap_CallInstance);
  Mock.esp_lcd_panel_set_gap_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_set_gap_CallInstance);
  if (Mock.esp_lcd_panel_set_gap_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_set_gap_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_set_gap_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_set_gap_CallbackBool &&
      Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer(panel, x_gap, y_gap, Mock.esp_lcd_panel_set_gap_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_set_gap,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_set_gap,CMockString_x_gap);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_x_gap, x_gap, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_set_gap,CMockString_y_gap);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_y_gap, y_gap, cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer(panel, x_gap, y_gap, Mock.esp_lcd_panel_set_gap_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_set_gap(CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, int x_gap, int y_gap);
void CMockExpectParameters_esp_lcd_panel_set_gap(CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, int x_gap, int y_gap)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_x_gap = x_gap;
  cmock_call_instance->Expected_y_gap = y_gap;
}

void esp_lcd_panel_set_gap_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_set_gap_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_set_gap_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_set_gap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_set_gap_IgnoreBool = (char)1;
}

void esp_lcd_panel_set_gap_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_set_gap_IgnoreBool)
    Mock.esp_lcd_panel_set_gap_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_set_gap_CallInstance);
  Mock.esp_lcd_panel_set_gap_IgnoreBool = (char)0;
}

void esp_lcd_panel_set_gap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, int x_gap, int y_gap, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_set_gap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_set_gap_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_set_gap_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_set_gap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_set_gap(cmock_call_instance, panel, x_gap, y_gap);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_set_gap_AddCallback(CMOCK_esp_lcd_panel_set_gap_CALLBACK Callback)
{
  Mock.esp_lcd_panel_set_gap_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_set_gap_CallbackBool = (char)1;
  Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_set_gap_Stub(CMOCK_esp_lcd_panel_set_gap_CALLBACK Callback)
{
  Mock.esp_lcd_panel_set_gap_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_set_gap_CallbackBool = (char)0;
  Mock.esp_lcd_panel_set_gap_CallbackFunctionPointer = Callback;
}

esp_err_t esp_lcd_panel_mirror(esp_lcd_panel_handle_t panel, bool mirror_x, bool mirror_y)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_mirror);
  cmock_call_instance = (CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_mirror_CallInstance);
  Mock.esp_lcd_panel_mirror_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_mirror_CallInstance);
  if (Mock.esp_lcd_panel_mirror_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_mirror_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_mirror_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_mirror_CallbackBool &&
      Mock.esp_lcd_panel_mirror_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_mirror_CallbackFunctionPointer(panel, mirror_x, mirror_y, Mock.esp_lcd_panel_mirror_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_mirror,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_mirror,CMockString_mirror_x);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_mirror_x, mirror_x, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_mirror,CMockString_mirror_y);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_mirror_y, mirror_y, cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_mirror_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_mirror_CallbackFunctionPointer(panel, mirror_x, mirror_y, Mock.esp_lcd_panel_mirror_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_mirror(CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool mirror_x, bool mirror_y);
void CMockExpectParameters_esp_lcd_panel_mirror(CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool mirror_x, bool mirror_y)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_mirror_x = mirror_x;
  cmock_call_instance->Expected_mirror_y = mirror_y;
}

void esp_lcd_panel_mirror_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_mirror_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_mirror_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_mirror_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_mirror_IgnoreBool = (char)1;
}

void esp_lcd_panel_mirror_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_mirror_IgnoreBool)
    Mock.esp_lcd_panel_mirror_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_mirror_CallInstance);
  Mock.esp_lcd_panel_mirror_IgnoreBool = (char)0;
}

void esp_lcd_panel_mirror_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool mirror_x, bool mirror_y, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_mirror_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_mirror_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_mirror_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_mirror_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_mirror(cmock_call_instance, panel, mirror_x, mirror_y);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_mirror_AddCallback(CMOCK_esp_lcd_panel_mirror_CALLBACK Callback)
{
  Mock.esp_lcd_panel_mirror_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_mirror_CallbackBool = (char)1;
  Mock.esp_lcd_panel_mirror_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_mirror_Stub(CMOCK_esp_lcd_panel_mirror_CALLBACK Callback)
{
  Mock.esp_lcd_panel_mirror_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_mirror_CallbackBool = (char)0;
  Mock.esp_lcd_panel_mirror_CallbackFunctionPointer = Callback;
}

esp_err_t esp_lcd_panel_disp_on_off(esp_lcd_panel_handle_t panel, bool on_off)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_disp_on_off);
  cmock_call_instance = (CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_disp_on_off_CallInstance);
  Mock.esp_lcd_panel_disp_on_off_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_disp_on_off_CallInstance);
  if (Mock.esp_lcd_panel_disp_on_off_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_disp_on_off_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_disp_on_off_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_disp_on_off_CallbackBool &&
      Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer(panel, on_off, Mock.esp_lcd_panel_disp_on_off_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_disp_on_off,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_disp_on_off,CMockString_on_off);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_on_off, on_off, cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer(panel, on_off, Mock.esp_lcd_panel_disp_on_off_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_disp_on_off(CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool on_off);
void CMockExpectParameters_esp_lcd_panel_disp_on_off(CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool on_off)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_on_off = on_off;
}

void esp_lcd_panel_disp_on_off_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_disp_on_off_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_disp_on_off_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_disp_on_off_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_disp_on_off_IgnoreBool = (char)1;
}

void esp_lcd_panel_disp_on_off_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_disp_on_off_IgnoreBool)
    Mock.esp_lcd_panel_disp_on_off_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_disp_on_off_CallInstance);
  Mock.esp_lcd_panel_disp_on_off_IgnoreBool = (char)0;
}

void esp_lcd_panel_disp_on_off_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool on_off, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_disp_on_off_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_disp_on_off_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_disp_on_off_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_disp_on_off_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_disp_on_off(cmock_call_instance, panel, on_off);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_disp_on_off_AddCallback(CMOCK_esp_lcd_panel_disp_on_off_CALLBACK Callback)
{
  Mock.esp_lcd_panel_disp_on_off_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_disp_on_off_CallbackBool = (char)1;
  Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_disp_on_off_Stub(CMOCK_esp_lcd_panel_disp_on_off_CALLBACK Callback)
{
  Mock.esp_lcd_panel_disp_on_off_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_disp_on_off_CallbackBool = (char)0;
  Mock.esp_lcd_panel_disp_on_off_CallbackFunctionPointer = Callback;
}

esp_err_t esp_lcd_panel_swap_xy(esp_lcd_panel_handle_t panel, bool swap_xy)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_lcd_panel_swap_xy);
  cmock_call_instance = (CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_lcd_panel_swap_xy_CallInstance);
  Mock.esp_lcd_panel_swap_xy_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_swap_xy_CallInstance);
  if (Mock.esp_lcd_panel_swap_xy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_lcd_panel_swap_xy_FinalReturn;
    memcpy((void*)(&Mock.esp_lcd_panel_swap_xy_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_lcd_panel_swap_xy_CallbackBool &&
      Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer(panel, swap_xy, Mock.esp_lcd_panel_swap_xy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_swap_xy,CMockString_panel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel), sizeof(esp_lcd_panel_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_lcd_panel_swap_xy,CMockString_swap_xy);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_swap_xy, swap_xy, cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer(panel, swap_xy, Mock.esp_lcd_panel_swap_xy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_lcd_panel_swap_xy(CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool swap_xy);
void CMockExpectParameters_esp_lcd_panel_swap_xy(CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE* cmock_call_instance, esp_lcd_panel_handle_t panel, bool swap_xy)
{
  memcpy((void*)(&cmock_call_instance->Expected_panel), (void*)(&panel),
         sizeof(esp_lcd_panel_handle_t[sizeof(panel) == sizeof(esp_lcd_panel_handle_t) ? 1 : -1])); /* add esp_lcd_panel_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_swap_xy = swap_xy;
}

void esp_lcd_panel_swap_xy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_swap_xy_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_swap_xy_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_swap_xy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_lcd_panel_swap_xy_IgnoreBool = (char)1;
}

void esp_lcd_panel_swap_xy_CMockStopIgnore(void)
{
  if(Mock.esp_lcd_panel_swap_xy_IgnoreBool)
    Mock.esp_lcd_panel_swap_xy_CallInstance = CMock_Guts_MemNext(Mock.esp_lcd_panel_swap_xy_CallInstance);
  Mock.esp_lcd_panel_swap_xy_IgnoreBool = (char)0;
}

void esp_lcd_panel_swap_xy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_lcd_panel_handle_t panel, bool swap_xy, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE));
  CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_lcd_panel_swap_xy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_lcd_panel_swap_xy_CallInstance = CMock_Guts_MemChain(Mock.esp_lcd_panel_swap_xy_CallInstance, cmock_guts_index);
  Mock.esp_lcd_panel_swap_xy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_lcd_panel_swap_xy(cmock_call_instance, panel, swap_xy);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_lcd_panel_swap_xy_AddCallback(CMOCK_esp_lcd_panel_swap_xy_CALLBACK Callback)
{
  Mock.esp_lcd_panel_swap_xy_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_swap_xy_CallbackBool = (char)1;
  Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer = Callback;
}

void esp_lcd_panel_swap_xy_Stub(CMOCK_esp_lcd_panel_swap_xy_CALLBACK Callback)
{
  Mock.esp_lcd_panel_swap_xy_IgnoreBool = (char)0;
  Mock.esp_lcd_panel_swap_xy_CallbackBool = (char)0;
  Mock.esp_lcd_panel_swap_xy_CallbackFunctionPointer = Callback;
}

