/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
/* injected defines for unity settings, etc */
#ifndef UNITY_EXCLUDE_FLOAT
#define UNITY_EXCLUDE_FLOAT
#endif /* UNITY_EXCLUDE_FLOAT */
#ifndef UNITY_INCLUDE_CONFIG_H
#define UNITY_INCLUDE_CONFIG_H
#endif /* UNITY_INCLUDE_CONFIG_H */
#include "Esp_menu.h"
#include "esp_timer.h"
#include "sdkconfig.h"
#include "esp_lcd_panel_io.h"
#include "esp_lvgl_port.h"
#include "esp_lcd_panel_vendor.h"
#include "esp_lcd_panel_ops.h"
#include "esp_err.h"
#include "esp_log.h"
#include "esp_system.h"
#include "mock_i2c_master.h"
#include "mock_esp_lcd_panel_io.h"
#include "mock_esp_lcd_panel_vendor.h"
#include "mock_esp_lcd_panel_ops.h"
#include "mock_gpio.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_menu_init(void);
extern void test_menu_draw(void);
extern void test_encoder_isr_handler(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_i2c_master_Init();
  mock_esp_lcd_panel_io_Init();
  mock_esp_lcd_panel_vendor_Init();
  mock_esp_lcd_panel_ops_Init();
  mock_gpio_Init();
}
static void CMock_Verify(void)
{
  mock_i2c_master_Verify();
  mock_esp_lcd_panel_io_Verify();
  mock_esp_lcd_panel_vendor_Verify();
  mock_esp_lcd_panel_ops_Verify();
  mock_gpio_Verify();
}
static void CMock_Destroy(void)
{
  mock_i2c_master_Destroy();
  mock_esp_lcd_panel_io_Destroy();
  mock_esp_lcd_panel_vendor_Destroy();
  mock_esp_lcd_panel_ops_Destroy();
  mock_gpio_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_Esp_menu.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_menu_init");
      UNITY_PRINT_EOL();
      UnityPrint("  test_menu_draw");
      UNITY_PRINT_EOL();
      UnityPrint("  test_encoder_isr_handler");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_Esp_menu.c");
  run_test(test_menu_init, "test_menu_init", 115);
  run_test(test_menu_draw, "test_menu_draw", 146);
  run_test(test_encoder_isr_handler, "test_encoder_isr_handler", 160);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
